name: push-to-EC2

#trigger deployment when something pushed to main branch

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files 123
        uses: actions/checkout@v2

  
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets. HOST_DNS }}
          username: ${{ secrets. USERNAME }}
          key: ${{ secrets. EC2_SSH_KEY }}
          script: |
            cd git-actions-repo
            sh deploy.sh
